apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
        - name: rust-api
          image: zot:5000/proyecto2/rust-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: BIND
              value: "0.0.0.0:8080"
            - name: GO_API_URL
              value: "http://go-deploy1-svc:8080"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: rust-api-svc
  namespace: proyecto2
spec:
  selector:
    app: rust-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
