controller:
  service:
    type: ClusterIP
  ingressClassResource:
    name: nginx
  ingressClass: nginx

  image:
    registry: zot:5000
    image: ingress-nginx/controller

admissionWebhooks:
  patch:
    image:
      registry: zot:5000
      image: ingress-nginx/kube-webhook-certgen
  createSecretJob:
    image:
      registry: zot:5000
      image: ingress-nginx/kube-webhook-certgen
