apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-go-b
  namespace: proyecto2
  labels:
    app: writer-go-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer-go-b
  template:
    metadata:
      labels:
        app: writer-go-b
    spec:
      containers:
        - name: writer-go-b
          image: writer-go-b:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: KAFKA_BROKER
              value: "kafka-service:29092"
            - name: KAFKA_TOPIC
              value: "ventas"
            - name: GRPC_PORT
              value: "50051"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: writer-go-b-svc
  namespace: proyecto2
  labels:
    app: writer-go-b
spec:
  type: ClusterIP
  selector:
    app: writer-go-b
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
